services:
  db-master:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PORT_NUMBER=${DB_PORT}
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - db-master-data:/bitnami/postgresql
    networks:
      - todo-network

  db-slave:
    image: bitnami/postgresql:latest
    depends_on:
      - db-master
    environment:
      - POSTGRESQL_PORT_NUMBER=${DB_PORT}
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=${DB_PORT}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD} 
    volumes:
      - db-slave-data:/bitnami/postgresql
    networks:
      - todo-network

  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db-master
      - db-slave
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - todo-network


  web-app:
    build: ./todo-server
    restart: always
    depends_on:
      - db-master
      - db-slave
    deploy:
      replicas: 2
    environment:
      - DB_HOST=db-master
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - todo-network

  # todo-fe:
  #   build: ./todo-frontend
  #   restart: always
  #   networks:
  #     - todo-network

  log-analyzer:
    image: allinurl/goaccess:latest
    container_name: log-analyzer
    restart: always
    networks:
      - todo-network
    ports:
      - "${LOGS_PORT}:7890"
    volumes:
      - nginx-logs:/opt/goaccess/logs:ro
      - log-report:/var/www/html
    entrypoint: ["goaccess", "/opt/goaccess/logs/access.log", "--log-format=COMBINED", "--real-time-html", "--addr=0.0.0.0", "--port=7890", "--ws-url=wss://localhost:8443/ws", "--output=/var/www/html/index.html"]

  reverse-proxy:
    image: nginx:alpine
    extra_hosts:
      - "host.docker.internal:host-gateway" # added this to work with fe not being a container
    ports:
      - "${PROXY_HTTP_PORT}:8080"
      - "${PROXY_HTTPS_PORT}:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - nginx-logs:/var/log/nginx
      - log-report:/usr/share/nginx/html/reports:ro
    depends_on:
      - web-app
      # - todo-fe # not sure i need this here
      - log-analyzer
    networks:
      - todo-network

      
networks:
  todo-network:
    driver: bridge
    
volumes:
  db-master-data:
  db-slave-data:
  nginx-logs:
  log-report:
  pgadmin-data: