events {
    worker_connections 1024;
}

http {

    upstream backend_servers {
        server web-app:80; # Docker DNS automatically finds both replicas
    }

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;
    
    server {
        listen 8080;
        server_name localhost;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 8443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            # proxy_pass http://todo-fe:5173; 
            proxy_pass http://host.docker.internal:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {

            # inainte nu functiona round-robin. cumva nginx pornea si vedea doar un singur web-server nu doua si mereu 
            # trimitea la acelasi cand puneam for i in {1..10}; do curl -k https://localhost:8443/api/; echo ""; done. Ca sa
            #  rezolv trebuia sa resetez nginx container (docker exec load-balanced-todo-app-reverse-proxy-1 nginx -s reload).
            # Dupa ce am rearanjat putin serverele in docker-compose.yml si am pus depends-on pentru db la majoritatea acum
            # functioneaza
            allow 127.0.0.1; # Allow your local network
            allow 172.16.0.0/12;  # Allow Docker internal network
            deny all;

            # resolver 127.0.0.11 valid=5s;
            set $backend_route http://backend_servers;
            proxy_pass $backend_route/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /logs {
            alias /usr/share/nginx/html/reports/;
            index index.html;
        }

        location /ws {
            proxy_pass http://log-analyzer:7890;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
